// NOTES
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS'
export const ADD_NOTE_FAILED = 'ADD_NOTE_FAILED'
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS'
export const EDIT_NOTE_FAILED = 'EDIT_NOTE_FAILED'
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS'
export const DELETE_NOTE_FAILED = 'DELETE_NOTE_FAILED'

//TASKS


//USER